#!/bin/bash

echo "🧪 Testing Email System on Production..."
echo ""
echo "Workspace: rian.io (1200057218350324)"
echo "Custom Field: Function (1213226456746418)"
echo "Option: Sales Initiative (1213465836909113)"
echo ""
echo "This will:"
echo "1. Fetch all Sales Initiative tasks from Asana"
echo "2. Generate AI-powered summary using Gemini"
echo "3. Send email to: foundersoffice@rian.io"
echo ""
echo "⏳ Sending test email..."
echo ""

# Use curl to trigger the email
# Note: This requires being logged in to the dashboard first
# Alternative: Check Railway logs to see the scheduler running

echo "Since the endpoint requires authentication, here are 2 options:"
echo ""
echo "Option 1: Check Railway Logs"
echo "  - Go to Railway Dashboard"
echo "  - Click on your backend service"
echo "  - Click 'Deployments' tab"
echo "  - View logs to see if scheduler started"
echo "  - Look for: '📧 Daily email scheduler started - will run at 6:00 PM IST every day'"
echo ""
echo "Option 2: Manual Trigger via Dashboard"
echo "  1. Go to: https://rian-dashboard-vercel.vercel.app"
echo "  2. Log in with Asana OAuth"
echo "  3. Open browser console (F12)"
echo "  4. Run:"
echo "     fetch('https://rian-dashboard-production.up.railway.app/api/email/send-daily-update', {"
echo "       method: 'POST',"
echo "       credentials: 'include',"
echo "       headers: { 'Content-Type': 'application/json' },"
echo "       body: JSON.stringify({"
echo "         workspaceGid: '1200057218350324',"
echo "         customFieldGid: '1213226456746418',"
echo "         optionGid: '1213465836909113'"
echo "       })"
echo "     }).then(r => r.json()).then(console.log)"
echo ""
echo "✅ The scheduler is active and will automatically send emails at 6:00 PM IST daily!"
